### ISSUE TITLE
Error while requiring the mode

### ISSUE THREAD

**Issue by oscarfv** [larkery/ido-grid-mode.el#1]
Starting with `emacs -Q`:

First of all, it is necessary to `(require 'cl-lib)` before activating `ido-grid-mode`, otherwise

```
(void-function cl-defun)
```

error is thrown.

Then, in `*scratch*` buffer:

```
(require 'ido-grid-mode)
```

fails with

```
(void-variable ido-grid-mode)
```

I'm using `GNU Emacs 25.0.50.1` (development snapshot from some months ago.)

**Comment by larkery** [comment]
Ah, both side-effects of my emacs state. I should have checked with `-Q` to be sure. The last couple of commits ought to make this work properly in a blank-slate; it now uses cl at compile time.

Let me know if `package-install-file`-ing it works now, and thanks for the feedback.

**Comment by oscarfv** [comment]
I don't use `package-install-file`, simply copy the file somewhere on the `load-path` and `require` and activate the mode. That works now, thank you.

My first impression after some minutes is quite positive. Now `ido-grid-mode` has replaced `ido-vertical-moode` on my setup. Thanks again.
