### ISSUE TITLE
File name completing in wrong directory

### ISSUE THREAD

**Issue by a-fent** [larkery/ido-grid-mode.el#6]
Let's say I have three files, known to ido

```
/dir/subdir/foo-bar.pdf
/dir/subdir/foo-bar.tex
/dir/foo-bar.org
```

I want to open the last. So I start typing the first few letters "foo". With ido-grid-mode enabled, I see first "no match", hit TAB, then I see the matching files. I use **<down>** to select the last and hit **<ENTER>**. However, it opens a blank file - emacs is then visiting /dir/subdir/foo-bar.org - i.e. the right name in the wrong directory.

I don't experience this with ido-vertical-mode.

**Comment by larkery** [comment]
I will try and reproduce the thing you describe but I am not entirely sure I follow from your description yet.

**Comment by larkery** [comment]
I cannot reproduce what you describe yet. If I am working in `dir` and I do `C-x C-f` `foo` `TAB` I end up with `/dir/foo-bar.org` as the only match and `RET` opens it. When you say the files are known to ido I am not sure what you mean either.

This could be to do with the way `ido-grid-mode` hooks into the tab key - if you customize `ido-grid-mode-keys` and disable `tab` and `backtab` it won't touch the bindings for those keys, which might help?

If you could write a list of things to do to exactly reproduce that would be very helpful, something like:

run this script to create the folder structure

```
mkdir -p /tmp/bug/subdir/
touch /tmp/bug/subdir/foo-bar.pdf
...
```

Then visit the file X / dired Y / whatever, and then do
`C-x C-f` `f` `o` `o` `TAB` ...

That might make it clearer.

**Comment by a-fent** [comment]
Thanks for the quick reply. I had a feeling this might be tricky to 
reproduce. But I have just done a run-through that reproduces it from 
scratch. The issue, more precisely, is fetching things from the ido-last 
list when nothing in the current directory matches. The behaviour with 
ido-grid doesn't match ido or ido-vertical.

mkdir bug
touch bug/foo-bar.one
mkdir bug/subdir
touch bug/subdir/foo-bar.two

visit foo-bar.one and foo-bar.two, perhaps type some text in them, close 
them, so they are saved in ido-last.

In another directory, C-x C-f f o o

with ido and ido-vertical (assuming there's nothing in the directory 
that matches), a list of recently visited files, including the two 
files, is presented. As I use ← and → to cycle through, the path matched 
shown is updated and I can open each file with <ENTER>.

When ido-grid is active, initially "No Match" is shown. If I tap <TAB> 
or →, it first says "Arithmetic Error", then a list is shown. However, 
if I cycle through the list with <up> and <down>, the matched file 
sometimes has the right name (foo-bar.two) but is shown in the wrong 
path (/bug, not /bug/subdir), and clicking <ENTER> will visit a new file.

**Comment by larkery** [comment]
Sounds like this is to do with virtual buffers or something similar I will see whether I can get the same outcome. The odd thing is that `ido-grid-mode` happens after anything to do with generating the list of suggestions. Just for information, do you have any other ido things going on (e.g. `flx`)?

**Comment by a-fent** [comment]
I don't think I have anything else relevant activated. For info, I'm on Emacs 24.5, have the problem on both Linux and Windows.

In case it helps, here's the backtrace for the "Arithmetic Error" which flashes up when I click TAB, when there are no matches in the current directory, in order to get a list of matched recently-used files from ido-last.

```
 Debugger entered--Lisp error: (arith-error)
   ido-grid-mode-move(1 0)
   ido-grid-mode-down()
   call-interactively(ido-grid-mode-down)
   ido-grid-mode-next()
   call-interactively(ido-grid-mode-next)
   ido-grid-mode-tab()
   call-interactively(ido-grid-mode-tab)
   ido-complete()
   call-interactively(ido-complete nil nil)
   command-execute(ido-complete)
   read-from-minibuffer("Find file: ~/Documents/Misc/bug/" "foo" (keymap (18 . ido-grid-mode-previous) (19 . ido-grid-mode-next) (16 . ido-grid-mode-previous-page) (14 . ido-grid-mode-next-page) (right . ido-grid-mode-right) (left . ido-grid-mode-left) (down . ido-grid-mode-down) (up . ido-grid-mode-up) (backtab . ido-grid-mode-previous) keymap (27 keymap (108 . ido-toggle-literal)) (23 . ido-copy-current-file-name) (15 . ido-copy-current-word) (11 . ido-delete-file-at-head) keymap (27 keymap (115 . ido-merge-work-directories) (112 . ido-prev-work-directory) (15 . ido-next-work-file) (111 . ido-prev-work-file) (110 . ido-next-work-directory) (109 . ido-make-directory) (107 . ido-forget-work-directory) (102 . ido-wide-find-file-or-pop-dir) (118 . ido-push-dir-first) (98 . ido-push-dir) (100 . ido-wide-find-dir-or-delete-dir)) (12 . ido-reread-directory) (C-backspace . ido-up-directory) (remap keymap (backward-kill-word . ido-delete-backward-word-updir) (delete-backward-char . ido-delete-backward-updir)) (127 . ido-delete-backward-updir) (backspace . ido-delete-backward-updir) (M-down . ido-next-work-directory) (M-up . ido-prev-work-directory) (up . ido-prev-match-dir) (down . ido-next-match-dir) (24 keymap (4 . ido-enter-dired) (6 . ido-fallback-command) (2 . ido-enter-switch-buffer)) keymap (4 . ido-magic-delete-char) (6 . ido-magic-forward-char) (2 . ido-magic-backward-char) (63 . ido-completion-help) (left . ido-prev-match) (right . ido-next-match) (0 . ido-restrict-to-matches) (27 keymap (32 . ido-take-first-match)) (67108896 . ido-restrict-to-matches) (26 . ido-undo-merge-work-directory) (20 . ido-toggle-regexp) (67108908 . ido-prev-match) (67108910 . ido-next-match) (19 . ido-next-match) (18 . ido-prev-match) (16 . ido-toggle-prefix) (13 . ido-exit-minibuffer) (10 . ido-select-text) (32 . ido-complete-space) (9 . ido-complete) (5 . ido-edit-input) (3 . ido-toggle-case) ...) nil ido-file-history)
   byte-code("\305\306 \"\n\307\307\f%\207" [item prompt ido-text-init ido-completion-map hist read-from-minibuffer ido-make-prompt nil] 6)
   ido-read-internal(file "Find file: " ido-file-history nil confirm-after-completion nil)
   ido-file-internal(raise-frame)
   ido-find-file()
   call-interactively(ido-find-file nil nil)
   command-execute(ido-find-file)
```

**Comment by larkery** [comment]
Thanks - I fix that error anyway, as it's ugly. I may have some time for elisp wrangling tonight, so hopefully some progress then.

**Comment by larkery** [comment]
Argh - whatever this does, it causes my emacs install to hang for an extended period, when it says 'searching for foo...' in the echo area! And that's with normal ido. I am not sure what it's doing when it says that. Whatever it is doing I can't stop it with `C-g` and it takes several seconds.

Do you have any ido configuration going on that affects the history stuff by the way? I don't really use it so I may have a different baseline to yours.

**Comment by larkery** [comment]
Argh, it runs a shell find command which seems to cause some bad IO wait situation for some reason for me. Probably trying to do find inside a network mount or something awful like that.

**Comment by larkery** [comment]
OK - having fixed that issue I can now get the intended behaviour and the fault. I will have to dig through the ido source to work out how it's meant to work. I have never used this feature of ido!

**Comment by larkery** [comment]
I am a bit stuck on how to fix this - I think the only fix is to copy paste a fairly large function out of ido and modify it to behave better, which is a bit ugly. I will see whether I can think of another way, but unfortunately I don't think I can avoid it without breaking support for `flx` which lots of people use.

**Comment by larkery** [comment]
I have made a commit which appears to fix this, without copy-pasting big chunks of `ido`. It will make the thing a little less efficient than I would like but it seems less hacky. Let me know if it either fixes the bug or produces more bugs!

**Comment by a-fent** [comment]
That looks like a complicated patch - but it seems to solve the bug and other things seem to be working as expected. Thank you!

PS I don't think I have anything unusual affecting ido-last, other than saving the file in a machine specific directory, my ido set-up is:

```
(setq ido-save-directory-list-file 
      (concat emacs-persistence-directory "ido.last"))
(ido-mode 1)

;; FFAP-ing
(setq ido-use-filename-at-point 'guess)

;; Which file types IDO prefers: look for org files first
(setq ido-file-extensions-order
      '(".org" ".txt" ".csv" ".r" ".el" ".tex" ".pdf" ".ini" ".cfg" ".cnf"))

;; Which file types find + IDO ignores
(setq completion-ignored-extensions
      (append
       completion-ignored-extensions
       ;; some extra latex ones (.blg .toc .aux already there)
       '(".bcf" ".run.xml" ".out" ".log" ".xdv" ".fls" ".fdb_latexmk") ) )
```
